services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-cloudgames
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - cloudgames-network

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cloudgames-network

  api:
    build:
      context: ./src
      dockerfile: FIAP.CloudGames.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
      - mongodb
    networks:
      - cloudgames-network
    restart: on-failure

volumes:
  sql_data:
  mongo_data:

networks:
  cloudgames-network:
    driver: bridge
