name: Trigger auto deployment for fiapcloudgames-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/fiapcloudgames-api-AutoDeployTrigger-abd7d5dc-2869-48c7-a28f-e72f2c8787fe.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FIAPCLOUDGAMESAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FIAPCLOUDGAMESAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FIAPCLOUDGAMESAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fiapcloudgamesacr.azurecr.io
          registryUsername: ${{ secrets.FIAPCLOUDGAMESAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FIAPCLOUDGAMESAPI_REGISTRY_PASSWORD }}
          containerAppName: fiapcloudgames-api
          resourceGroup: ACR
          imageToBuild: fiapcloudgamesacr.azurecr.io/fiapcloudgames-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


