name: FIAPCloudGames

on:
  push:
    branches: [ master, github-actions ]

jobs:
  build:
    runs-on: ubunto-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
